### ISSUE TITLE
Planning : Fixing Bugs : Backlog

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/agile-development-group2-loruki#16]
I created a Backlog branch before but apparently that branch was nested to User Persona branch.
To fix that problem I deleted my previous backlog branch and created a new one from master branch.

Lesson learnt: **Everytime I want to create a new branch I ALWAYS need to go to the master branch first. And then create a new branch from there. Otherwise I will create a nested branch, which WRONG.**

# Task

- Creating  Backlog

## Status 
- [x] In progress
- [ ] Need Revision 
- [ ] Done 

### Details 
After creating User Personas we can define all their needs. We lists their needs and divided into;
Must Have, Should Have, and Could have.

- [x] Must Have is a mandatory things that they want to see on our website
- [x] Should Have is want they want to see but less important
- [x] Could Have is just an extra things that they want to see but are not important at all
