### ISSUE TITLE
Planning : Updating : Communication.md

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/agile-development-group2-loruki#17]
# Task
- [x]  Updating Communication.md using the newest branch name; planning/communication-md

## Things that need to be edited in file `communication.md`:

- [x] Week dates
- [ ] Member availability hours;
    Gabriella : Monday to Friday; 19u - 02u
    Ali : Monday to Friday; whole day
    Cemal : Monday-Friday; whole day
    Gopi : ??

## Make sure to do this steps:

- [ ] Go to VSCode
- [ ] Go to your previous communication branch
- [ ] Copy your communication.md file 
- [ ] `git checkout master` --> To go to Master Branch
- [ ] `git branch` --> To see branches you have on your local/git
- [ ] `git branch -D <branch name you want to delete>`  --> To delete branch
- [ ] `git branch` --> To see branches you have on your git, to make sure that the previous branch is deleted
- [ ] `git pull`
- [ ] `git checkout planning/communication-md`
- [ ]  Paste your previous work in `communication.md` and edit what you need to edit
- [ ] `git status`
- [ ] `git add <name of files you modified>`
- [ ] `git commit -m "<message>" ---> **Take a good look on constraints.md about our standard format for commit message**
- [ ] run the npm check. **Make sure you passed all the linting before push** Except for result from `npm run spell-check`
- [ ] `git pull origin master`
- [ ] `git push origin planning/communication-md`

When you create a PR don't forget to attach it with this issue. You can search for this issue on `development` coloumn on your right side when creating a PR
