### ISSUE TITLE
Creating Backlog based on user personas

### ISSUE THREAD

**Issue by GabriellaLohy** [HYF-Class20/agile-development-group2-loruki#7]
# Task

- Creating  Backlog

## Status 
- [x] In progress
- [x] Need Revision 
- [ ] Done 

### Details 
After creating User Personas we can define all their needs. We lists their needs and divided into;
Must Have, Should Have, and Could have.

- [ ] Must Have is a mandatory things that they want to see on our website
- [ ] Should Have is want they want to see but less important
- [ ] Could Have is just an extra things that they want to see but are not important at all
